load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")
load("//tools:cpplint.bzl", "cpplint")

package(default_visibility = ["//visibility:public"])


cc_library(
    name = "lib_include",
    hdrs = [
        "Arithmetic.h",
        "Bistable.h",
        "Comm.h",
        "Comparison.h",
        "Control.h",
        "Converter.h",
        "Counter.h",
        "Driver.h",
        "Fsm.h",
        "IO.h",
        "Logic.h",
        "Maths.h",
        "Opencv.h",
        "Selection.h",
        "System.h",
        "Timer.h",
        "Task.h",
        "Trigger.h",
        "Geometry.h",
    ],
)
