load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")
load("//tools:cpplint.bzl", "cpplint")

package(default_visibility = ["//visibility:public"])


cc_binary(
    name = "calc_core",
    srcs = [
        "main.cc",

    ],
    linkopts = [

    ],
    linkstatic = False,
    deps = [
    ],
)



cpplint()
