load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")
load("//tools:cpplint.bzl", "cpplint")

package(default_visibility = ["//visibility:public"])


cc_library(
    name = "calc_gflags",
    includes = [
    ],
    hdrs = [
        "calc_gflags.h",

    ],
    srcs = [
        "calc_gflags.cpp",
    ],
    deps = [
        "@com_google_gflags_gflags//:gflags"
    ],
)




