load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "String",
    srcs = [
        "String.cpp",
    ],
    hdrs = [
        "ADD_DOUBLE",
        "ADD_FLOAT",
        "ADD_INT",
        "ADD_INT64",
        "ADD_TIME",
        "ADD_UINT",
        "ADD_UINT64",
        "DIV_DOUBLE",
        "DIV_FLOAT",
        "DIV_INT",
        "DIV_INT64",
        "DIV_UINT",
        "DIV_UINT64",
        "MOVE_BOOL",
        "MOVE_DOUBLE",
        "MOVE_FLOAT",
        "MOVE_INT",
        "MOVE_INT64",
        "MOVE_UINT",
        "MOVE_UINT64",
        "MUL_DOUBLE",
        "MUL_FLOAT",
        "MUL_INT",
        "MUL_INT64",
        "MUL_UINT",
        "MUL_UINT64",
        "SUB_DOUBLE",
        "SUB_FLOAT",
        "SUB_INT",
        "SUB_INT64",
        "SUB_TIME",
        "SUB_UINT",
        "SUB_UINT64",
    ],
    includes = [
    ],
    deps = [
        "//modules/calc/include:calc_include",
        "//modules/calc/include/lib:lib_include",
        "//modules/calc/proto:bus_cc_proto",
    ],
)
