load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")
load("//tools:cpplint.bzl", "cpplint")

package(default_visibility = ["//visibility:public"])


cc_library(
    name = "calc_include",
    hdrs = [
        "cfgbus.h",
        "evbus.h",
        "k_command.h",
        "k_compress.h",
        "k_config.h",
        "k_datatype.h",
        "k_evdata.h",
        "k_functionblock.h",
        "k_id.h",
        "k_io.h",
        "k_lib.h",
        "k_process.h",
        "k_program.h",
        "k_project.h",
        "k_state.h",
        "k_util.h",
        "nic_calc_adapter.h",
        "nic_calc_IDmap.h",
        "nic_calc_IO.h",
        "nic_calc_tag.h",
        "nic_calc_util.h",
        "precomp.h",
        "stbbus.h",
        "vnet.h",
        "vtcp.h",
        "vudp.h"
    ],
)
